RegisterToggle("Auto Fish", function(v) end)
RegisterToggle("Fish Assist", function(v) end)
RegisterToggle("Fish Legit", function(v) end)
RegisterToggle("Zone Detector", function(v) end)
RegisterToggle("Rod Optimizer", function(v) end)
RegisterSlider("Delay Controller", 1)

RegisterToggle("Fast Action", function(v) end)
RegisterToggle("Instant Mode", function(v) end)
RegisterToggle("Anti Fail", function(v) end)

RegisterToggle("Anti AFK", function(v) end)
RegisterButton("Auto Rejoin", function() end)
RegisterButton("FPS Boost", function() end)
RegisterButton("Server Hop", function() end)
RegisterSlider("UI Speed", 1)
